### PR TITLE
add --reject option

### PR DESCRIPTION
**Pull request by mechanomi**
specifically:

- refactor main image processing loop

  previously, input files were copied all at once to the output directory
  (which could be the same as the input location) and then (potentially)
  destructive changes were made on those files

  this changeset refactors this proces loop so that image files are handled one
  by one

  this means that, in a typical use scenario, images with a face that can be
  detected will be moved to the output directory and then cropped, leaving a
  directory of images that could not be cropped (because no face was detected)

  this is a backwards incompatible change

- modify file handling to not use absolute paths. this improves output logging

- improve output logging

- added a `--reject` option

  when supplied, images where no face was detected will be moved to the
  specified rejected directory

### CODE REVIEW

**Comment by mechanomi** [comment]
unresolve issues:

[ ] needs at least one test for `--skip` option
[ ] needs at least one test for `--filter` option

@leblancfg I was hoping you could provide me with some guidance here. I have been trying to create a couple of tests, but I am not sure how to do it

**Comment by mechanomi** [comment]
I originally made this PR to add `--skip` and `--filter` options. but through further experimentation, I have found that a `--reject` option is easier to understand and provides better functionality

**Comment by leblancfg** [comment]
Thank you so much for this @mechanomi!

I really want to make sure the pull request gets merged, specifically for the *crop-before-copy* change, which is so evident now that you highlight it. I'd like to make sure that all the tests pass first though. I was able to pull your PR locally, and it looks like there are 5 tests that now fail. I'll have to take a deeper dive and see where that comes from &mdash; might be as simple as changing the arguments for the function calls.

As for using the absolute path, I vaguely remember there being a good reason for it... which I forget. This might account for some of the test failures.

In the meantime, could you add an extra test for the `reject` feature? I **haven't tested it myself**, but something along the lines of:

```python
def test_reject_flag_puts_noface_images_in_reject_folder(integration):
    sys.argv = ['', '-i', 'tests/test', '-o', 'tests/crop', '-r', 'tests/reject']
    cli()
    output_files = os.listdir(sys.argv[4])
    rejected_files = os.listdir(sys.argv[-1])
    assert len(output_files) == 9
    assert len(rejected_files) == 1
```

**Comment by leblancfg** [comment]
As for using absolute paths, I vaguely remember there being a good reason for it... which I promptly forget now. This probably accounts for some of the test failures.

For this PR, suggest you revert using absolute paths, and I'll create a new issue to start using Pathlib for the paths. This way, we can use the best of both worlds by using the `Path.name` attribute for logging.

**Comment by mechanomi** [comment]
@leblancfg sorry for the delay. have been quite busy this week

I've made some fixup changes, rebased, and force pushed to my branch

changes made:

- revert the abspath changes as requested
- fix most style errors
- fix most tests

I am stuck, however, on these items:

- I am seeing a `FutureWarning` message for flake8

  ```
  Running flake8 
  /Users/nomi/Documents/GitHub/mechanomi/autocrop/env/lib/python3.7/site-packages/pycodestyle.py:113: FutureWarning: Possible nested set at position 1
    EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
  0
  ```

- there is one remaining test failure that I can't wrap my head around

  ```
  _____________________ test_images_files_copied_over_if_output_dir_specified _____________________

  integration = None

      @mock.patch('autocrop.autocrop.crop', lambda *args: None)
      def test_images_files_copied_over_if_output_dir_specified(integration):
          sys.argv = ['', '-i', 'tests/test', '-o', 'tests/crop']
          cli()
          output_files = os.listdir(sys.argv[-1])
  >       assert len(output_files) == 9
  E       assert 0 == 9
  E        +  where 0 = len([])

  tests/test_autocrop.py:232: AssertionError
  ```
  for some reason, when this test runs, none of the faces are detected (and so there's nothing in the output directory)

  if I manually set up the `tests/test` directory and run `autocrop` with the same arguments, it detects the faces as you would expect

in addition to the above, there is one remaining task:

- [ ] add a new test for the reject feature

**Comment by leblancfg** [comment]
Naomi, thanks so much for this. I'll take a look this afternoon and see what I can do.

I appreciate you sending over the update in its partial form. Two (and possibly more) heads are better than one! :smiley:

**Comment by leblancfg** [comment]
Got it. From the latest changelog:

~~~
0.2.0
Changes

    Add -o, --output flag to specify directory where cropped images are to be dumped.
        [...]
        If no face can be found in an image in batch, it is still copied over to -o folder.
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
~~~

Which, admittedly, was not documented anywhere in the code. :man_shrugging:

I've added the changes to overrule this behaviour if the `-reject` directory is used, which is the only way I can see people using both `-o` and `-r` flags would see it used.

### Action Required
I'm trying to push to this PR though so I don't have to force a merge to the master branch. Would you be able to [check the "Allow edits from maintainers" box](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/), please?

Push edits to PR

Thanks Naomi!

**Comment by mechanomi** [comment]
@leblancfg that setting seems to be checked already!

**Comment by leblancfg** [comment]
:man_facepalming: :laughing:  Sorry about that, thanks!

Closes #48.

**Comment by mechanomi** [comment]
sweet! thanks!

**Pull request merged**
